#!/usr/bin/env bash
# Idempotent download of BSI TR-03161 PDFs into diga/regulations/pdf/.
# Re-running only re-downloads if the URL is reachable; sha256 + size are recorded
# in regulations/source-manifest.yaml.
#
# Usage: ./scripts/fetch-pdfs.sh
# Requires: curl, shasum, wc

set -euo pipefail

DIGA_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PDF_DIR="${DIGA_ROOT}/regulations/pdf"
MANIFEST="${DIGA_ROOT}/regulations/source-manifest.yaml"
mkdir -p "${PDF_DIR}"

# id | filename | url
DOCS=(
  "tr-03161-1|BSI-TR-03161-1.pdf|https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03161/BSI-TR-03161-1.pdf?__blob=publicationFile"
  "tr-03161-2|BSI-TR-03161-2.pdf|https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03161/BSI-TR-03161-2.pdf?__blob=publicationFile"
  "tr-03161-3|BSI-TR-03161-3.pdf|https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03161/BSI-TR-03161-3.pdf?__blob=publicationFile"
)

NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
{
  echo "# Auto-generated by scripts/fetch-pdfs.sh — do not edit by hand."
  echo "# Re-run the script after a regulation update; PRs surface the diff."
  echo "generated_at: \"${NOW}\""
  echo "documents:"
} > "${MANIFEST}"

for entry in "${DOCS[@]}"; do
  IFS='|' read -r id filename url <<<"${entry}"
  out="${PDF_DIR}/${filename}"
  echo ">>> ${id} → ${filename}"
  curl --fail --silent --show-error --location --user-agent "TwoBreath-DiGA-fetch/1.0" \
       --output "${out}" "${url}" \
    || { echo "!!! download failed for ${id}"; exit 1; }
  sha="$(shasum -a 256 "${out}" | awk '{print $1}')"
  bytes="$(wc -c < "${out}" | tr -d ' ')"
  {
    echo "  - id: ${id}"
    echo "    filename: ${filename}"
    echo "    url: \"${url}\""
    echo "    pdf_path: \"regulations/pdf/${filename}\""
    echo "    sha256: ${sha}"
    echo "    bytes: ${bytes}"
    echo "    downloaded_at: \"${NOW}\""
  } >> "${MANIFEST}"
done

echo
echo "Manifest written: ${MANIFEST}"
